# TODO: https://github.com/sorin-ionescu/dotfiles/blob/master/tmux.conf

if-shell 'test "$(uname)" = "Darwin"' 'source ~/.tmux-osx.conf'

set-option -g default-shell /bin/zsh
set-option -g allow-rename off
set-option -gw xterm-keys on
set-option -g base-index 1
set-option -g mouse on

# Prefix = C-\
#unbind-key 'C-b'
#set-option -g prefix 'C-\'
#bind-key 'C-\' send-prefix

# Start window indexing at one instead of zero.
set-option -g -w pane-base-index 1

bind -n Home send-key C-a
bind -n End send-key C-e
