set-option -g default-shell /bin/zsh
set-option -gw xterm-keys on
set-option -gw mode-keys vi

bind-key -t vi-copy 'v' begin-selection
bind-key -t vi-copy 'y' copy-selection

bind -n Home send-key C-a
bind -n End send-key C-e
