scriptencoding utf-8

" enable syntax-highlighting
syntax on

" GUI and Terminal VIM options
if has("gui_running")
  " Disable all GUI elements and enable console based dialogs for simple queries
  set guioptions=gc
  set guicursor=a:blinkon0
  set guifont=Menlo\ Regular:h11

  " sets the language of the menu
  set langmenu=en_US.UTF-8
else
  set t_Co=256
endif

" Mouse
if has('mouse')
  " Enable mouse support
  set mouse=a

  " Hide cursor while typing
  set mousehide
endif

" Multibyte
if has('multi_byte')
  "›,·,»·,¶,→,←,×,▸,¬,˽,˰
  set listchars=trail:·,tab:»\ ,extends:→,precedes:←,nbsp:×

  " Vertical split chars
  set fillchars=stl:\ ,stlnc:\ ,vert:│

  " Show ↪ at the beginning of wrapped lines
  let &sbr = nr2char(8618).' ' 
  set breakindent
  set breakindentopt=sbr
endif

" Autocmd
if has("autocmd")
  " Enable file type detection.
  filetype plugin indent on

  au FileType python     setlocal nosmartindent nonumber "textwidth=79
  au FileType perl       setlocal noexpandtab foldmethod=indent
  au FileType javascript setlocal expandtab shiftwidth=4 tabstop=4
  au FileType vim        setlocal expandtab shiftwidth=2 tabstop=2
  au FileType scss       setlocal expandtab shiftwidth=2 tabstop=2
  au FileType css        setlocal expandtab shiftwidth=4 tabstop=4
  au FileType html       setlocal expandtab shiftwidth=2 tabstop=2
  au FileType jinja      setlocal expandtab shiftwidth=2 tabstop=2
  au FileType yaml       setlocal expandtab shiftwidth=2 tabstop=2
  au FileType tex        setlocal updatetime=200
endif

if has("gui_macvim")
  " set macmeta
endif

" Store undofile in to fixed location
if exists("+undofile")
  set undofile

  if !isdirectory('~/.vim/undo')
    silent !mkdir -p ~/.vim/undo
  endif

  " Store undo files in fixed location
  set undodir=~/.vim/undo
endif
"

nnoremap <silent> <tab> :nohlsearch<return>

" Store swap files in fixed location
set noswapfile
set directory=/var/tmp//,/tmp//,.

" Store backup files in fixed location
set nobackup
set backupdir=/var/tmp//,/tmp//,.

" Set your path variable to current directory, and children
set path=.,,**

" Disable timeout for Esc key
set ttimeout ttimeoutlen=0 notimeout
set ttyfast " Optimize for fast terminal connections
set lazyredraw " Don't redraw while executing macros (good performance config)

" Autocomplete options:
" longest: do not select the first candidate
" preview: removed includes display of documentation
set completeopt=menuone,longest

set confirm " Get a dialog when :q, :w, or :wq fails

let mapleader = "\<Space>" " Map leader

let maplocalleader = "\<Backspace>" " Local leader

set hlsearch " Highlight search terms (very useful!)

set incsearch " Show search matches while typing

set display=lastline " Display lastline instead of @

set laststatus=2 " Enable statusline

set scrolloff=3 " Minimal number of screen lines to keep above and below the cursor

set magic " For regular expressions turn magic on

set ignorecase " Searches are Non Case-sensitive

set smartcase " Do smart case matching when searching

set showcmd " Show incomplete cmds down the bottom

set title " Show title

set noautochdir " Vim will not change the current working directory whenever you open a file

set autoread " Reload files changed outside automatically

set tabstop=4 " Number of spaces that a <Tab> in the file counts for

set softtabstop=0 " Number of spaces that a <Tab> counts for while performing editing operations

set shiftwidth=4 " Number of spaces to use for each step of (auto)indent

set expandtab " Use the appropriate number of spaces to insert a <Tab>

set backspace=indent,eol,start " Fix backspace indent

set smarttab " Be smart when using tabs

set autoindent " Enable auto indent

set smartindent " Smart indent

set wrap " Enable word wrap

set textwidth=0 " Disable line break

set noerrorbells novisualbell t_vb= " No annoying sound on errors

set encoding=utf8 " Default encoding

set termencoding=utf-8 " Terminal encoding

set fileencodings=utf8 " Supported file encodings

set nonumber " Enable line numbers

"set colorcolumn=80 " Show right margin

set list " Show non printable characters

set ruler " Always display cursor position

set hidden " A buffer becomes hidden when it is abandoned

set wildmenu " Turn on the Wild menu

set wildmode=list:longest,list:full " Wildmenu configuration

" Ignore files
set wildignore=*.o,*.obj,.git/**,node_modules/**,.sass-cache,*.pyc,*.gem
set wildignore+=*.jpg,*.jpeg,*.tiff,*.gif,*.png,*.svg,*.pdf

set conceallevel=0 " Conceal level

set modelines=1 " Make Vim only use folding settings for current file

set foldmethod=syntax

set foldminlines=1

set noshowmode " Suppress mode change messages

set exrc " Allow load .vimrc or _vimrc from current directory

set cursorline " Highlight the screen line of the cursor

" if empty(glob('~/.vim/autoload/plug.vim'))
"   silent !curl --fail --location --create-dirs --output ~/.vim/autoload/plug.vim
"         \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
"   autocmd VimEnter * PlugInstall --sync
" endif

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

if filereadable(expand('~/.vim/plugins.vim'))
  " Include plugins list
  source ~/.vim/plugins.vim
endif

set termguicolors
" let ayucolor="light"
" let ayucolor="mirage"
let ayucolor="dark"

try
  if has("gui_macvim")
    colorscheme ayu
  else
    colorscheme ayu
  endif
catch
endtry

" vim:foldmethod=marker:foldlevel=0:tabstop=2:shiftwidth=2
